platform :ios, '13.0'

use_frameworks!

target 'RxRequestCache_Example' do
  pod 'RxRequestCache', :path => '../'
  pod 'RxCocoa'

  target 'RxRequestCache_Tests' do
    inherit! :search_paths
  end
end
