use_frameworks!

target 'RxRequestCache_Example' do
  pod 'RxRequestCache', :path => '../'

  target 'RxRequestCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
